name: Setup Dioxus
description: Setup Dioxus environment

runs:
    using: composite
    steps:
        - uses: actions/cache@v4
          with:
              path: |
                  ~/.cargo/
                  ~/.dioxus/
                  ~/.rustup/
                  target/
              key: ${{ runner.os }}-cargo-{{ hashFiles('**/Cargo.lock') }}
        - uses: awalsh128/cache-apt-pkgs-action@latest
          with:
              packages: build-essential libwebkit2gtk-4.1-dev
              version: 1.0
              execute_install_scripts: true
        - uses: cargo-bins/cargo-binstall@main
        - name: Install Dioxus CLI
          shell: bash
          run: cargo binstall -y dioxus-cli@0.7.0-rc.0
        - name: Add additional Rustup targets
          shell: bash
          run: rustup target add wasm32-unknown-unknown
