name: CI

on:
    pull_request:
        branches: [main]
        paths-ignore:
            - .editorconfig
            - LICENCE
            - README.md

    push:
        branches: [main]
        paths-ignore:
            - .editorconfig
            - LICENCE
            - README.md

jobs:
    check_rust:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v5
            - uses: ./.github/actions/setup-dioxus
            - name: Check with cargo-clippy
              run: |
                  cargo clippy -- -D warnings || failed
                  cargo clippy --features core -- -D warnings || failed
                  cargo clippy --features app -- -D warnings || failed
                  cargo clippy --features web -- -D warnings || failed
                  cargo clippy --features desktop -- -D warnings || failed
                  cargo clippy --features mobile -- -D warnings || failed
                  cargo clippy --features server -- -D warnings || failed
                  cargo clippy --features auth-client -- -D warnings || failed
                  cargo clippy --features auth-client,build -- -D warnings || failed
                  cargo clippy --features auth-client,core -- -D warnings || failed
                  cargo clippy --features build -- -D warnings || failed
                  cargo clippy --features test-utils -- -D warnings || failed
            - name: Check with cargo-fmt
              run: cargo fmt --all --check
            - name: Check with dioxus-cli
              run: dx fmt --check

    check_css:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v5
            - uses: ./.github/actions/setup-node
            - name: Build sample CSS
              run: npx @tailwindcss/cli --minify --input ./style.css --output ./output.css
